# permissions for end users to view jobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-viewer-role
rules:
- apiGroups:
  - batch.liuyao.me
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.liuyao.me
  resources:
  - jobs/status
  verbs:
  - get
